let tagJson = {
  'Generator Reqd.': 'FALSE',
  'Test-By': 'Contrat3',
  'Supply-By': 'Contrat1',
  'GA-Drawing': ' ',
  Name: '5K1.BF01.FNJ01-M2001',
  Type: 'SC',
  'MCC-Bucket': '03E',
  'Con Cable Type': 'PL',
  Drive: 'FALSE',
  MCC: '61A',
  LRA: '0',
  Phase: '3',
  Premounted: 'TRUE',
  Desc: 'DUST COLLECTOR FAN 1',
  Frame: '326T',
  EFF: '94.5',
  'LOC-Drawing': ' ',
  'Power-Factor': '87',
  'Service-Factor': '0',
  Vendor: 'BALDOR',
  'Con Prewired': 'FALSE',
  'Install-By': 'Contrat2',
  'Connected to': '621.N112 (MCC 61A)',
  'Starter-Size': '3',
  HZ: '0',
  Desc2: 'Ventilateur 1 du d�poussi�reur',
  Area: '5K1',
  HP: '50',
  Notes: ' ',
  Certified: 'TRUE',
  Enclosure: 'TEFC',
  'PID-Drawing': '160.52.22-1133444',
  Rev: 'Q',
  'Load-Factor': '80',
  Voltage: '575 VAC',
  KW: '0',
  Speed: '1800',
  FLA: '45',
  Model: 'ECP84115T-5',
  Starter: 'FVNR',
  'Diversity-Factor': '95',
};

for (x in tagJson) {
  console.log(`${x} : ${tagJson[x]}`);
}
