var fs = require('fs');
// string generated by canvas.toDataURL()
var img =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0' +
  'NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO' +
  '3gAAAABJRU5ErkJggg==';
// strip off the data: url prefix to get just the base64-encoded bytes
var data = img.replace(/^data:image\/\w+;base64,/, '');
var buff = Buffer.from(data, 'base64');
console.log(buff);

// fs.writeFile('image.png', buf);
